#!/bin/bash
python train.py -p 5
python train.py -p 10
python train.py -p 15
python train.py -p 20
python train.py -p 25
python train.py -p 30
python train.py -p 35
python train.py -p 40
python train.py -p 45
python train.py -p 50
python train.py -p 55
python train.py -p 60
python train.py -p 65
python train.py -p 70
python train.py -p 75
python train.py -p 80
python train.py -p 85
python train.py -p 90
