#!/bin/bash
python train.py -p 61
python train.py -p 62
python train.py -p 63
python train.py -p 64
python train.py -p 66
python train.py -p 67
python train.py -p 68
python train.py -p 69
python train.py -p 71
python train.py -p 72
python train.py -p 73
python train.py -p 74
python train.py -p 76
python train.py -p 77
python train.py -p 78
python train.py -p 79
python train.py -p 81
python train.py -p 82
python train.py -p 83
python train.py -p 84
python train.py -p 86
python train.py -p 87
python train.py -p 88
python train.py -p 89
python train.py -p 91
python train.py -p 92
python train.py -p 93
python train.py -p 94
python train.py -p 95
